name: Dead Code Detection

on:
  pull_request:
    paths:
      - 'src/**'
      - 'pyproject.toml'

jobs:
  vulture:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install -e ".[dev]"
      - name: Run vulture
        # Blocking check - add genuine false positives to vulture_whitelist.py
        run: vulture src/ vulture_whitelist.py
